name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change this to your main branch name
  pull_request:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Change this to your desired Node.js version

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          yarn install -g vercel
          vercel --token $VERCEL_TOKEN --prod
